#define LARG_JANELA 800
#define ALT_JANELA 800

#define LARG_ORTHO 240
#define ALT_ORTHO 240
#define ZNEAR_ORTHO -1
#define ZFAR_ORTHO 1

#define TAM_BORDA_ESQ 20
#define TAM_BORDA_DIR 20
#define TAM_BORDA_INF 20
#define TAM_BORDA_SUP 20
#define NUM_LINHAS_INIMIGOS 4
#define NUM_COLUNAS_INIMIGOS 7

#define NUM_VIDAS_JOGADOR 3

#define NUM_TIROS_JOGADOR 30
#define NUM_TIROS_INIMIGOS 10

#define LARG_JOGADOR 20
#define ALT_JOGADOR 20

#define ALT_TIRO_JOG 5
#define LARG_TIRO_JOG 3
#define VEL_TIRO_JOG 5

#define ALT_TIRO_INIM 5
#define LARG_TIRO_INIM 3
#define VEL_TIRO_INIM 2

#define LARG_VIDA 10
#define ALT_VIDA 10

#define LARG_PAUSE 20
#define ALT_PAUSE 20

#define FRAMES_INTERVALO_TIROS 10

#define TELA_MENU 0
#define TELA_JOGO 1
#define TELA_PERDEU 2
#define TELA_GANHOU 3
#define TELA_CREDITOS 4
#define TELA_CONTROLES 5
